export declare enum InterstitialButtonTypes {
    NA = "NA",
    IN_APP = "IN_APP",
    LINK = "LINK",
    MEDIA_FCM_V2 = "MEDIA_FCM_V2",
    VIEW_UI_CATEGORY = "VIEW_UI_CATEGORY",
    SUBSCRIPTION_LANDING = "SUBSCRIPTION_LANDING",
    TAB_LANDING = "TAB_LANDING",
    DOWNLOADS_PAGE = "DOWNLOADS_PAGE",
    REELS_PAGE = "REELS_PAGE",
    LIVE_PAGE = "LIVE_PAGE",
    UPCOMING_PAGE = "UPCOMING_PAGE",
    SUPPORT_PAGE = "SUPPORT_PAGE",
    RATE_NOW_FCM = "RATE_NOW_FCM",
    DIALOG_FCM = "DIALOG_FCM",
    OPEN_SIDE_MENU = "OPEN_SIDE_MENU",
    REFERRAL_PAGE = "REFERRAL_PAGE",
    CELEBRITY_LIVE = "CELEBRITY_LIVE"
}
