export enum ClientContentType {

  ABOUT = "ABOUT",
  TERMS_OF_USE = "TERMS_CONDITIONS",
  REFUND_POLICY = "REFUND_POLICY",
  PRIVACY_POLICY = "PRIVACY_POLICY",
  CONTACT_INFORMATION = "CONTACT_INFORMATION"
}
